---
# see https://oss.help/87382-16
- name: mask atopacctd in LXD
  systemd:
    name: atopacct
    masked: yes
  when: ansible_virtualization_type == "lxc"

- name: Enable EPEL repo
  package:
    name:
      - "epel-release"
      - "{{ 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-' +
        ansible_distribution_major_version +
        '.noarch.rpm'
        }}"
    state: present
    disable_gpg_check: True # Workaround for GPG fail on RHEL 8
  tags:
    - atop
  ignore_errors: true
  when: ansible_os_family == "RedHat"

- name: Install atop Redhat
  package:
    name: "{{ item }}"
    state: present
  tags:
    - atop
  loop: "{{ atop_packages }}"
  when: ansible_os_family == "RedHat"

- name: install packages on Debian
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
    cache_valid_time: 86400
  loop: "{{ atop_packages }}"
  when: ansible_os_family == "Debian"

- name: ensure atop service is started and enabled
  service:
    name: atop
    enabled: true
    state: started

- name: acct service check
  service:
    name: acct
    enabled: true
  when: not atop_role_test_mode

- name: set daemon interval
  lineinfile:
    dest: "{{ atop_paths.env_file | default('/etc/default/atop') }}"
    regexp: "LOGINTERVAL"
    line: "LOGINTERVAL={{ atop_daemon_interval }}"
    create: yes
  notify: restart atop service
  when: not atop_role_test_mode

- name: acct enable
  lineinfile:
    dest: /etc/default/atop
    line: "ATOPACCT=/var/log/account/pacct"
    create: yes
  notify: restart atop service
  when: not atop_role_test_mode

- name: atoprc
  template:
    src: atoprc.j2
    dest: /root/.atoprc
